// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfm8E1UMUta7CesLum63fP8Je_uDe9WSE',
    appId: '1:843748462662:web:82baa0cba910dc397ffa47',
    messagingSenderId: '843748462662',
    projectId: 'yuukey-9cd5d',
    authDomain: 'yuukey-9cd5d.firebaseapp.com',
    storageBucket: 'yuukey-9cd5d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmQI8KP3n2mY6eCoPNryZdWpRjFPSlN-c',
    appId: '1:843748462662:android:71805f641d8875247ffa47',
    messagingSenderId: '843748462662',
    projectId: 'yuukey-9cd5d',
    storageBucket: 'yuukey-9cd5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWt4hJyjvCiCBQiuH1Vg7cyopDQ0wY018',
    appId: '1:843748462662:ios:6fcb7cfbca84c7947ffa47',
    messagingSenderId: '843748462662',
    projectId: 'yuukey-9cd5d',
    storageBucket: 'yuukey-9cd5d.firebasestorage.app',
    iosBundleId: 'com.example.uidesign',
  );
}
